# Generated by Django 6.1 on 2026-08-30 14:40

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('work', '0003_jobitem_service_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('translation_key', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('asset_kinds', models.JSONField(blank=True, default=list)),
                ('vehicle_classes', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('builtin', 'Built in'), ('user', 'Yours'), ('imported', 'Imported')], default='builtin', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('area', models.CharField(choices=[('road_test', 'Road test'), ('under_hood', 'Under hood'), ('under_vehicle', 'Under vehicle'), ('brakes', 'Brakes'), ('tires_wheels', 'Tires and wheels'), ('suspension_steering', 'Suspension and steering'), ('lighting_electrical', 'Lighting and electrical'), ('body_glass', 'Body and glass'), ('interior', 'Interior'), ('fluids', 'Fluids'), ('exhaust_emissions', 'Exhaust and emissions')], default='under_hood', max_length=24)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=160)),
                ('translation_key', models.CharField(blank=True, max_length=80)),
                ('guidance', models.TextField(blank=True, help_text="What 'good' looks like.")),
                ('result_type', models.CharField(choices=[('status', 'Pass / attention / fail'), ('measurement', 'A number'), ('both', 'Both')], default='status', max_length=12)),
                ('measurement_unit', models.CharField(blank=True, max_length=16)),
                ('positions', models.JSONField(blank=True, default=list)),
                ('sub_positions', models.JSONField(blank=True, default=list)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('photo_required', models.CharField(choices=[('never', 'Not needed'), ('on_attention', 'When flagged'), ('always', 'Always')], default='never', max_length=12)),
                ('is_safety_critical', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='inspections.inspectiontemplate')),
            ],
            options={
                'ordering': ['area', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('template_name', models.CharField(max_length=120)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('points_snapshot', models.JSONField(default=list, help_text='The template as it stood. Later edits never rewrite this inspection.')),
                ('performed_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('draft', 'In progress'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], db_index=True, default='draft', max_length=12)),
                ('overall', models.CharField(blank=True, choices=[('pass', 'Pass'), ('attention', 'Attention'), ('fail', 'Fail'), ('not_applicable', 'Not applicable'), ('not_inspected', 'Not inspected')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='work.workorder')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.inspectiontemplate')),
            ],
            options={
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('point_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('point_snapshot', models.JSONField(default=dict)),
                ('position', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('attention', 'Attention'), ('fail', 'Fail'), ('not_applicable', 'Not applicable'), ('not_inspected', 'Not inspected')], max_length=16)),
                ('auto_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('attention', 'Attention'), ('fail', 'Fail'), ('not_applicable', 'Not applicable'), ('not_inspected', 'Not inspected')], help_text='What the thresholds computed, kept alongside what the human decided.', max_length=16)),
                ('status_overridden', models.BooleanField(default=False)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('converted_to_job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_inspection', to='work.jobitem')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspections.inspection')),
            ],
            options={
                'ordering': ['point_snapshot__area', 'point_snapshot__sequence', 'position'],
                'indexes': [models.Index(fields=['inspection', 'status'], name='inspections_inspect_0b1122_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['asset', '-performed_on'], name='inspections_asset_i_28f993_idx'),
        ),
    ]
