# Generated by Django 6.1 on 2026-08-30 16:02

from django.db import migrations, models


def refile_fluids(apps, schema_editor):
    """Move template points out of the retired "fluids" area.

    Template points are current configuration, so they are re-filed. Recorded
    results are **not** touched: `inspection_result.point_snapshot` is history,
    and rewriting it would change what a past inspection says it checked. Those
    rows keep `area = "fluids"` and still render, because `area_display` falls
    back to a titled version of the key.
    """
    InspectionPoint = apps.get_model("inspections", "InspectionPoint")
    InspectionPoint.objects.filter(area="fluids").update(area="under_hood")


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionpoint',
            name='area',
            field=models.CharField(choices=[('road_test', 'Road test'), ('under_hood', 'Under hood'), ('under_vehicle', 'Under vehicle'), ('brakes', 'Brakes'), ('tires_wheels', 'Tires and wheels'), ('suspension_steering', 'Suspension and steering'), ('lighting_electrical', 'Lighting and electrical'), ('body_glass', 'Body and glass'), ('interior', 'Interior'), ('exhaust_emissions', 'Exhaust and emissions')], default='under_hood', max_length=24),
        ),
        migrations.RunPython(refile_fluids, migrations.RunPython.noop),
    ]
