# Generated by Django 6.1 on 2026-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspectionpoint_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='author',
            field=models.CharField(blank=True, help_text='Who published this, where it came from a shared catalog.', max_length=80),
        ),
    ]
