# Generated by Django 6.1 on 2026-08-30 05:29

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediafiles', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('nickname', models.CharField(help_text='What the household actually calls it — “the red truck”.', max_length=120)),
                ('asset_kind', models.CharField(choices=[('vehicle', 'Vehicle'), ('equipment', 'Equipment')], default='vehicle', max_length=16)),
                ('vehicle_class', models.CharField(blank=True, choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('trailer', 'Trailer'), ('rv', 'RV'), ('bus', 'Bus'), ('other_plated', 'Other plated')], max_length=16)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('project', 'Project'), ('stored', 'Stored'), ('sold', 'Sold'), ('parted_out', 'Parted out'), ('totaled', 'Totaled')], db_index=True, default='active', max_length=16)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=32)),
                ('vin_status', models.CharField(choices=[('valid', 'Validated'), ('unvalidated', 'Not validated'), ('pre_1981', 'Pre-1981 format'), ('none', 'No VIN')], default='none', max_length=16)),
                ('plate', models.CharField(blank=True, max_length=16)),
                ('plate_region', models.CharField(blank=True, help_text='State or province.', max_length=8)),
                ('plate_expires_on', models.DateField(blank=True, null=True)),
                ('title_state', models.CharField(blank=True, max_length=32)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('trim', models.CharField(blank=True, max_length=64)),
                ('body_style', models.CharField(blank=True, max_length=64)),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('fuel_type', models.CharField(blank=True, max_length=32)),
                ('transmission', models.CharField(blank=True, max_length=64)),
                ('drivetrain', models.CharField(blank=True, max_length=32)),
                ('color_exterior', models.CharField(blank=True, max_length=48)),
                ('manufacturer', models.CharField(blank=True, max_length=64)),
                ('model_number', models.CharField(blank=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('meter', models.CharField(choices=[('odometer', 'Odometer'), ('engine_hours', 'Engine hours'), ('cycles', 'Cycles'), ('none', 'No meter')], default='odometer', max_length=16)),
                ('meter_unit', models.CharField(default='mi', max_length=8)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('decode_source', models.CharField(blank=True, max_length=32)),
                ('decoded_at', models.DateTimeField(blank=True, null=True)),
                ('decoded_raw', models.JSONField(blank=True, default=dict)),
                ('field_overrides', models.JSONField(blank=True, default=dict, help_text='Fields the operator corrected; a re-decode must never clobber these.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediafiles.media')),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('co_owner', 'Co-owner'), ('primary_driver', 'Primary driver')], default='owner', max_length=16)),
                ('from_date', models.DateField(default=django.utils.timezone.localdate)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to='people.person')),
            ],
            options={
                'verbose_name_plural': 'asset ownerships',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInfoProvider',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('base_urls', models.JSONField(default=list, help_text='Ordered mirror list; the first reachable one wins.')),
                ('url_template', models.CharField(blank=True, help_text='Tokens: {make} {year} {model}. Only as deep as the pattern is reliable.', max_length=255)),
                ('deep_link_depth', models.CharField(choices=[('root', 'Site root only'), ('make', 'Make'), ('make_year', 'Make and year')], default='make_year', max_length=16)),
                ('access', models.CharField(choices=[('free', 'Free, no sign-up'), ('paid', 'Paid subscription'), ('account', 'Account required')], default='free', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetServiceInfoLink',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('subscription_status', models.CharField(choices=[('subscribed', 'Subscribed'), ('not_subscribed', 'Not subscribed'), ('unknown', 'Unknown')], default='unknown', help_text='ALLDATA DIY is sold per vehicle, so this is per asset.', max_length=20)),
                ('subscription_expires_on', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_info_links', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='assets.serviceinfoprovider')),
            ],
            options={
                'ordering': ['provider__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UsageReading',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('meter', models.CharField(default='odometer', max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='mi', max_length=8)),
                ('value_canonical', models.DecimalField(decimal_places=4, editable=False, max_digits=14)),
                ('read_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('manual', 'Entered by hand'), ('work_order', 'From a work order'), ('obd', 'Scan tool'), ('document', 'From a document'), ('import', 'Imported')], default='manual', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_rollback', models.BooleanField(default=False, help_text='Set when the reading decreases — allowed, but it needs an explanation.')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_readings', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_kind', 'status'], name='assets_asse_asset_k_0cf379_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'nickname'], name='assets_asse_status_02dee7_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetserviceinfolink',
            constraint=models.UniqueConstraint(fields=('asset', 'provider'), name='unique_asset_provider_link'),
        ),
        migrations.AddIndex(
            model_name='usagereading',
            index=models.Index(fields=['asset', '-read_on'], name='assets_usag_asset_i_6608e6_idx'),
        ),
    ]
