# Generated by Django 6.1 on 2026-08-30 14:54

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('mediafiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSpec',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('group', models.CharField(choices=[('fluids', 'Fluids and capacities'), ('torque', 'Torque specs'), ('tires', 'Tires and wheels'), ('electrical', 'Electrical'), ('alignment', 'Alignment'), ('filters', 'Filters and part numbers'), ('access', 'Keys and access codes'), ('other', 'Other')], default='other', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('condition', models.CharField(blank=True, help_text='e.g. “cold, curb weight” — a spec without its condition is a guess.', max_length=120)),
                ('source', models.CharField(choices=[('manual', "Owner's manual"), ('oem_doc', 'OEM document'), ('measured', 'Measured'), ('decoded', 'From a VIN decode'), ('other', 'Other')], default='manual', max_length=16)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Hidden from reports and shared exports. Key and radio codes belong here.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Show in the quick-reference panel on work orders.')),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_media', models.ForeignKey(blank=True, help_text='The page it came from (FR-SPEC-2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mediafiles.media')),
            ],
            options={
                'ordering': ['group', 'name'],
                'indexes': [models.Index(fields=['asset', 'group'], name='assets_asse_asset_i_3cf7fc_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'group', 'name', 'condition'), name='unique_asset_spec')],
            },
        ),
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('campaign_number', models.CharField(blank=True, max_length=48)),
                ('nhtsa_id', models.CharField(blank=True, max_length=48)),
                ('reported_on', models.DateField(blank=True, null=True)),
                ('component', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('consequence', models.TextField(blank=True)),
                ('remedy', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('nhtsa', 'NHTSA'), ('manual', 'Entered by hand')], default='nhtsa', max_length=12)),
                ('owner_status', models.CharField(choices=[('open', 'Not checked'), ('scheduled', 'Scheduled'), ('completed', 'Done'), ('not_applicable', 'Does not apply to this VIN')], default='open', max_length=16)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_on', 'campaign_number'],
                'constraints': [models.UniqueConstraint(fields=('asset', 'campaign_number'), name='unique_asset_recall')],
            },
        ),
    ]
