# Generated by Django 6.1 on 2026-08-30 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetspec_recall'),
        ('mediafiles', '0002_remove_medialink_unique_media_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetserviceinfolink',
            name='unique_asset_provider_link',
        ),
        migrations.RemoveConstraint(
            model_name='assetspec',
            name='unique_asset_spec',
        ),
        migrations.RemoveConstraint(
            model_name='recall',
            name='unique_asset_recall',
        ),
        migrations.AddConstraint(
            model_name='assetserviceinfolink',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'provider'), name='unique_asset_provider_link'),
        ),
        migrations.AddConstraint(
            model_name='assetspec',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'group', 'name', 'condition'), name='unique_asset_spec'),
        ),
        migrations.AddConstraint(
            model_name='recall',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'campaign_number'), name='unique_asset_recall'),
        ),
    ]
