# Generated by Django 6.1 on 2026-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_assetserviceinfolink_unique_asset_provider_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetspec',
            name='source',
            field=models.CharField(choices=[('manual', "Owner's manual"), ('oem_doc', 'OEM document'), ('measured', 'Measured'), ('decoded', 'From a VIN decode'), ('scan_tool', 'Read from a scan tool'), ('other', 'Other')], default='manual', max_length=16),
        ),
    ]
