# Generated by Django 6.1 on 2026-08-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assetspec_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetserviceinfolink',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden for this vehicle. CHARM has no entry for a 2025 Crosstrek and never will, so a permanent empty box is worse than no box (OQ-11).'),
        ),
        migrations.AlterField(
            model_name='assetserviceinfolink',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
