# Generated by Django 6.1 on 2026-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetserviceinfolink_is_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfoprovider',
            name='dtc_path',
            field=models.CharField(blank=True, help_text="Path from the vehicle root to this library's DTC index, if it has one.", max_length=300),
        ),
    ]
