# Generated by Django 6.1 on 2026-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_serviceinfoprovider_dtc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetspec',
            name='value_max',
            field=models.CharField(blank=True, help_text='Only for a spec that is a range. Leave blank for a single figure.', max_length=200, verbose_name='to'),
        ),
    ]
