# Generated by Django 6.1 on 2026-09-01 04:03

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_spec_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLink',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, help_text='Why this is worth keeping — the thing you would forget.', max_length=300)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', '-created_at'],
            },
        ),
    ]
