# Generated by Django 6.1 on 2026-09-04 15:51

import django.db.models.deletion
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_assetlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCardPreference',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('board_order', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('pins', models.JSONField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_preferences', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['board_order'],
                'indexes': [models.Index(fields=['user', 'board_order'], name='assets_asse_user_id_826c2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'asset'), name='unique_asset_card_preference')],
            },
        ),
    ]
