# Generated by Django 6.1 on 2026-09-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_assetcardpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='recalls_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
