# Generated by Django 6.1 on 2026-08-30 05:29

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('number', models.CharField(editable=False, max_length=24, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('diagnosis', 'Diagnosis'), ('modification', 'Modification'), ('inspection', 'Inspection'), ('project', 'Project')], default='repair', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('waiting_on_parts', 'Waiting on parts'), ('on_hold', 'On hold'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], db_index=True, default='planned', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 highest, 5 lowest.')),
                ('complaint', models.TextField(blank=True, help_text="What is wrong, in the reporter's words.")),
                ('cause', models.TextField(blank=True, help_text='What you found.')),
                ('correction', models.TextField(blank=True, help_text='What you did about it.')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('odometer_in', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('odometer_out', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('blocked_reason', models.TextField(blank=True, help_text='Required while waiting on parts, so the dashboard can explain itself.')),
                ('is_safety_critical', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='A long project collects child work orders while staying one record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='work.workorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_work', to='people.person')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('doing', 'In progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='todo', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='work.workorder')),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNote',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('body', models.TextField()),
                ('noted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='work.workorder')),
            ],
            options={
                'ordering': ['-noted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', '-opened_at'], name='work_workor_status_670cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset', '-opened_at'], name='work_workor_asset_i_91314f_idx'),
        ),
    ]
