# Generated by Django 6.1 on 2026-08-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('work', '0002_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='Completing this rolls that maintenance interval forward (FR-WO-7).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_items', to='maintenance.assetserviceitem'),
        ),
    ]
