# Generated by Django 6.1 on 2026-08-30 20:23

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_jobitem_service_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTool',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('tool_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('lifecycle', models.CharField(blank=True, max_length=32)),
                ('on_loan_to', models.CharField(blank=True, max_length=80)),
                ('loan_due_on', models.DateField(blank=True, null=True)),
                ('from_kit', models.CharField(blank=True, max_length=80)),
                ('calibration_due_on', models.DateField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobItemTool',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='work.jobitem')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='work.shoptool')),
            ],
            options={
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('job_item', 'tool'), name='unique_job_item_tool')],
            },
        ),
    ]
