# Generated by Django 6.1 on 2026-08-31 05:30

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_partcrossref_unique_crossref_and_more'),
        ('work', '0004_shoptool_jobitemtool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequirement',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('origin', models.CharField(choices=[('planned', 'Planned'), ('discovered', 'Found once it was apart')], default='planned', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_item', models.ForeignKey(blank=True, help_text='Which line of work needs it. Optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requirements', to='work.jobitem')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='parts.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requirements', to='work.workorder')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['work_order'], name='work_partre_work_or_4cc6a0_idx'), models.Index(fields=['part'], name='work_partre_part_id_846f27_idx')],
            },
        ),
    ]
