# Generated by Django 6.1 on 2026-08-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_partrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='revision',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
