# Generated by Django 6.1 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_time_entries_are_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'time entries'},
        ),
    ]
