# Generated by Django 6.1 on 2026-09-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_timeentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='budget_currency',
            field=models.CharField(blank=True, default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='workorder',
            name='budget_minor',
            field=models.BigIntegerField(blank=True, default=None, help_text='Minor units (e.g. cents). Never a float.', null=True, verbose_name='budget'),
        ),
    ]
