# Generated by Django 6.1 on 2026-08-30 06:26

import django.utils.timezone
import homeautoshop.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRef',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_instance_url', models.CharField(blank=True, max_length=255)),
                ('external_type', models.CharField(max_length=48)),
                ('external_id', models.CharField(max_length=128)),
                ('entity_type', models.CharField(db_index=True, max_length=48)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('first_imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('linked', 'Linked'), ('orphaned', 'Gone from the source'), ('conflicted', 'Changed on both sides')], default='linked', max_length=12)),
            ],
            options={
                'indexes': [models.Index(fields=['source_system', 'external_type'], name='core_extern_source__dd2060_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_instance_url', 'external_type', 'external_id'), name='unique_external_ref')],
            },
        ),
    ]
