# Generated by Django 6.1 on 2026-08-30 15:07

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_externalref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], default='email', max_length=12)),
                ('target', models.CharField(help_text='Email address, or the URL to POST to.', max_length=500)),
                ('is_enabled', models.BooleanField(default=False)),
                ('include_routine', models.BooleanField(default=True, help_text='Include routine items, not just safety and overdue.')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for a shop-wide channel.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('dedupe_key', models.CharField(db_index=True, max_length=200)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='core.notificationchannel')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['channel', 'dedupe_key', '-sent_at'], name='core_notifi_channel_74a976_idx')],
            },
        ),
    ]
