# Generated by Django 6.1 on 2026-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificationchannel_notificationsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='subscription',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('webpush', 'Phone notification')], default='email', max_length=12),
        ),
    ]
