# Generated by Django 6.1 on 2026-08-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificationchannel_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ciphertext', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
    ]
