# Generated by Django 6.1 on 2026-08-30 06:09

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('work', '0002_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reason', models.CharField(choices=[('receive', 'Received'), ('consume', 'Used on a job'), ('adjust', 'Cycle count adjustment'), ('return', 'Returned to vendor'), ('scrap', 'Scrapped'), ('found', 'Found')], max_length=12)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parts.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('manufacturer', models.CharField(blank=True, max_length=80)),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=80)),
                ('part_type', models.CharField(choices=[('oem', 'OEM'), ('oe_supplier', 'OE supplier'), ('aftermarket', 'Aftermarket'), ('remanufactured', 'Remanufactured'), ('used', 'Used')], default='aftermarket', max_length=20)),
                ('unit', models.CharField(choices=[('each', 'each'), ('L', 'litres'), ('kg', 'kilograms'), ('ft', 'feet')], default='each', max_length=8)),
                ('is_consumable', models.BooleanField(default=False)),
                ('has_core', models.BooleanField(default=False)),
                ('core_value_minor', models.BigIntegerField(blank=True, default=None, help_text='Minor units (e.g. cents). Never a float.', null=True, verbose_name='core value')),
                ('core_value_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('hazmat_class', models.CharField(blank=True, max_length=32)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Restock below this. Blank means never prompt.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Viscosity, thread pitch, dimensions.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartCrossRef',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('system', models.CharField(choices=[('oem', 'OEM'), ('interchange', 'Interchange'), ('vendor_sku', 'Vendor SKU'), ('upc', 'UPC')], default='interchange', max_length=16)),
                ('value', models.CharField(db_index=True, max_length=80)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs', to='parts.part')),
            ],
            options={
                'ordering': ['system', 'value'],
            },
        ),
        migrations.CreateModel(
            name='PartFitment',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('make', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_code', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, max_length=32)),
                ('confidence', models.CharField(choices=[('confirmed_installed', 'Confirmed — installed on this vehicle'), ('stated_by_vendor', 'Stated by vendor'), ('unverified', 'Unverified')], default='unverified', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitments', to='parts.part')),
            ],
            options={
                'ordering': ['confidence', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_cost_minor', models.BigIntegerField(blank=True, default=None, help_text='Minor units (e.g. cents). Never a float.', null=True, verbose_name='unit cost')),
                ('unit_cost_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('source', models.CharField(choices=[('from_stock', 'From the shelf'), ('purchased_for_job', 'Bought for this job'), ('reused', 'Reused'), ('warranty', 'Warranty replacement')], default='from_stock', max_length=20)),
                ('core_returned', models.BooleanField(default=False)),
                ('core_returned_on', models.DateField(blank=True, null=True)),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('installed_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='work.jobitem')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='parts.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='work.workorder')),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_cost_minor', models.BigIntegerField(blank=True, default=None, help_text='Minor units (e.g. cents). Never a float.', null=True, verbose_name='unit cost')),
                ('unit_cost_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('acquired_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, help_text='Brake fluid, RTV and epoxy do expire.', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='parts.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='parts.part')),
            ],
            options={
                'ordering': ['acquired_on', 'created_at'],
            },
        ),
    ]
