# Generated by Django 6.1 on 2026-08-30 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('work', '0002_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='purchase_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='purchasing.purchaseline'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='parts.stocklot'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parts.stocklot'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_moves', to='work.workorder'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category', 'name'], name='parts_part_categor_28b15f_idx'),
        ),
        migrations.AddConstraint(
            model_name='partcrossref',
            constraint=models.UniqueConstraint(fields=('part', 'system', 'value'), name='unique_crossref'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['part', 'acquired_on'], name='parts_stock_part_id_1e6afd_idx'),
        ),
    ]
