# Generated by Django 6.1 on 2026-08-30 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='partcrossref',
            name='unique_crossref',
        ),
        migrations.AddConstraint(
            model_name='partcrossref',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('part', 'system', 'value'), name='unique_crossref'),
        ),
    ]
