# Generated by Django 6.1 on 2026-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_remove_partcrossref_unique_crossref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partfitment',
            name='confidence',
            field=models.CharField(choices=[('confirmed_installed', 'Confirmed — installed on this vehicle'), ('does_not_fit', 'Does not fit — tried it'), ('stated_by_vendor', 'Stated by vendor'), ('unverified', 'Unverified')], default='unverified', max_length=24),
        ),
    ]
