# Generated by Django 6.1 on 2026-08-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_partfitment_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(choices=[('receive', 'Received'), ('consume', 'Used on a job'), ('adjust', 'Cycle count adjustment'), ('return', 'Returned to vendor'), ('scrap', 'Scrapped'), ('found', 'Found'), ('unreceive', 'Receipt reversed')], max_length=12),
        ),
    ]
