# Generated by Django 6.1 on 2026-08-31 18:24

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_alter_stocktransaction_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='from_kit_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_lots', to='parts.stocklot'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(choices=[('receive', 'Received'), ('consume', 'Used on a job'), ('adjust', 'Cycle count adjustment'), ('return', 'Returned to vendor'), ('scrap', 'Scrapped'), ('found', 'Found'), ('unreceive', 'Receipt reversed'), ('kit_opened', 'Kit opened'), ('kit_closed', 'Kit put back together')], max_length=12),
        ),
        migrations.CreateModel(
            name='PartKitItem',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('value_share', models.DecimalField(decimal_places=3, default=1, help_text="Relative share of the kit's cost. Equal shares by default.", max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_items', to='parts.part')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_kits', to='parts.part')),
            ],
            options={
                'ordering': ['part__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('kit', 'part'), name='unique_kit_item')],
            },
        ),
    ]
