# Generated by Django 6.1 on 2026-08-31 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_serviceinfoprovider_dtc_path'),
        ('parts', '0007_kit_costs_in_money'),
        ('work', '0005_partrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='partusage',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_usages', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='work.workorder'),
        ),
    ]
