# Generated by Django 6.1 on 2026-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_usage_without_a_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='unit',
            field=models.CharField(choices=[('Counted', [('each', 'each')]), ('Weight', [('lb', 'pounds'), ('oz', 'ounces'), ('kg', 'kilograms'), ('g', 'grams')]), ('Volume', [('qt', 'quarts'), ('gal', 'gallons'), ('floz', 'fluid ounces'), ('L', 'litres'), ('ml', 'millilitres')]), ('Length', [('ft', 'feet'), ('in', 'inches'), ('m', 'metres')])], default='each', max_length=8),
        ),
    ]
