# Generated by Django 6.1 on 2026-09-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_categories_are_several'),
    ]

    operations = [
        migrations.AddField(
            model_name='partfitment',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='For a part that is not specific to a make or model at all.', verbose_name='fits any vehicle'),
        ),
    ]
