# Generated by Django 6.1 on 2026-09-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_partfitment_is_universal'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='supplier_url',
            field=models.URLField(blank=True, help_text='A link to this part at a supplier, for ordering another.', max_length=500, verbose_name='where to buy it'),
        ),
    ]
