# Generated by Django 6.1 on 2026-09-03 00:30

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0008_assetlink'),
        ('work', '0008_work_order_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluidSample',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('compartment', models.CharField(choices=[('engine_oil', 'Engine oil'), ('transmission', 'Transmission'), ('differential', 'Differential'), ('transfer_case', 'Transfer case'), ('hydraulic', 'Hydraulic'), ('coolant', 'Coolant'), ('brake_fluid', 'Brake fluid'), ('fuel', 'Fuel'), ('gear_oil', 'Gear oil'), ('other', 'Other')], db_index=True, default='engine_oil', max_length=16)),
                ('position', models.CharField(blank=True, help_text='Front, rear — where there is more than one.', max_length=16)),
                ('sampled_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('usage_at_sample', models.DecimalField(blank=True, decimal_places=2, help_text='The meter reading when the sample was drawn.', max_digits=12, null=True)),
                ('fluid_usage', models.DecimalField(blank=True, decimal_places=2, help_text='How far the fluid itself had run — miles or hours since it was changed. Wear metals accumulate, so without this a number cannot be compared with the last one.', max_digits=12, null=True)),
                ('fluid_changed', models.BooleanField(default=False, help_text='Was the fluid changed at this sample?')),
                ('lab', models.CharField(blank=True, max_length=120)),
                ('report_number', models.CharField(blank=True, max_length=64)),
                ('fluid_brand', models.CharField(blank=True, max_length=120)),
                ('fluid_grade', models.CharField(blank=True, help_text='5W-30, 75W-90…', max_length=32)),
                ('lab_comment', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_samples', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fluid_samples', to='work.workorder')),
            ],
            options={
                'ordering': ['-sampled_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FluidResult',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('analyte', models.CharField(db_index=True, max_length=48)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('reference', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('flagged', models.BooleanField(default=False, help_text='The lab marked this line. Their judgment, not ours.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fluids.fluidsample')),
            ],
            options={
                'ordering': ['analyte'],
            },
        ),
        migrations.AddIndex(
            model_name='fluidsample',
            index=models.Index(fields=['asset', 'compartment', '-sampled_on'], name='fluids_flui_asset_i_b23b15_idx'),
        ),
        migrations.AddConstraint(
            model_name='fluidresult',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('sample', 'analyte'), name='one_result_per_analyte_per_sample'),
        ),
    ]
