# Generated by Django 6.1 on 2026-08-30 05:29

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
import homeautoshop.mediafiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('scan_export', 'Scan tool report'), ('audio_note', 'Audio note')], default='photo', max_length=16)),
                ('file', models.FileField(max_length=500, upload_to=homeautoshop.mediafiles.models.upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('thumb', models.ImageField(blank=True, max_length=500, null=True, upload_to='derivatives/thumb/')),
                ('preview', models.ImageField(blank=True, max_length=500, null=True, upload_to='derivatives/preview/')),
                ('derived_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_status', models.CharField(choices=[('n/a', 'Not applicable'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='n/a', max_length=10)),
                ('gps_stripped', models.BooleanField(default=False, help_text='A photo of a car in a driveway geotags a home address.')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('entity_type', models.CharField(db_index=True, max_length=32)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('role', models.CharField(choices=[('primary_photo', 'Primary photo'), ('before', 'Before'), ('after', 'After'), ('receipt', 'Receipt'), ('manual', 'Manual'), ('title', 'Title'), ('registration', 'Registration'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mediafiles.media')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='mediafiles__entity__ca053b_idx')],
                'constraints': [models.UniqueConstraint(fields=('media', 'entity_type', 'entity_id', 'role'), name='unique_media_link')],
            },
        ),
    ]
