# Generated by Django 6.1 on 2026-09-01 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_remove_medialink_unique_media_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'media files'},
        ),
    ]
