# Generated by Django 6.1 on 2026-08-30 06:35

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('parts', '0002_initial'),
        ('work', '0002_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetServiceItem',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('interval_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(default='mi', max_length=8)),
                ('interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('last_done_on', models.DateField(blank=True, null=True)),
                ('last_done_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('next_due_on', models.DateField(blank=True, db_index=True, null=True)),
                ('next_due_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('snoozed', 'Snoozed'), ('disabled', 'Not tracked')], db_index=True, default='ok', max_length=12)),
                ('snooze_until', models.DateField(blank=True, null=True)),
                ('snooze_reason', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_on', 'definition__name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('translation_key', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('builtin', 'Built in'), ('user', 'Yours'), ('imported', 'Imported')], default='builtin', max_length=12)),
                ('asset_kinds', models.JSONField(blank=True, default=list)),
                ('vehicle_classes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCompletion',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('completed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_backfill', models.BooleanField(default=False, help_text='Recorded from history rather than from work done here (FR-MAINT-6).')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_completions', to='work.jobitem')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='maintenance.assetserviceitem')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_completions', to='work.workorder')),
            ],
            options={
                'ordering': ['-completed_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('translation_key', models.CharField(blank=True, help_text='Stable key so shipped items can be translated (SPEC §5.6).', max_length=80)),
                ('category', models.CharField(blank=True, max_length=48)),
                ('severity', models.CharField(choices=[('routine', 'Routine'), ('safety', 'Safety'), ('emissions', 'Emissions')], default='routine', max_length=12)),
                ('default_interval_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('default_interval_unit', models.CharField(default='mi', max_length=8)),
                ('default_interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('default_interval_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assetserviceitem',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='maintenance.servicedefinition'),
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('interval_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_unit', models.CharField(default='mi', max_length=8)),
                ('interval_months', models.PositiveIntegerField(blank=True, null=True)),
                ('interval_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='maintenance.servicedefinition')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.scheduletemplate')),
            ],
            options={
                'ordering': ['sequence', 'definition__name'],
            },
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('component_type', models.CharField(choices=[('tire', 'Tire'), ('battery', 'Battery'), ('brake_pad', 'Brake pad'), ('brake_rotor', 'Brake rotor'), ('belt', 'Belt'), ('filter', 'Filter'), ('wiper', 'Wiper'), ('bulb', 'Bulb'), ('other', 'Other')], default='other', max_length=16)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('position', models.CharField(blank=True, help_text='LF, RF, LR, RR…', max_length=16)),
                ('installed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('installed_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('removed_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('removal_reason', models.CharField(blank=True, choices=[('worn', 'Worn out'), ('failed', 'Failed'), ('upgraded', 'Upgraded'), ('seasonal', 'Seasonal change')], max_length=12)),
                ('serial_or_dot_code', models.CharField(blank=True, help_text='Tire DOT code: week and year of manufacture.', max_length=32)),
                ('warranty_months', models.PositiveIntegerField(blank=True, null=True)),
                ('warranty_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_life_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('installed_by_job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.jobitem')),
                ('part', models.ForeignKey(blank=True, help_text='Optional: a component may predate any part record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='parts.part')),
            ],
            options={
                'ordering': ['component_type', 'position', '-installed_on'],
                'indexes': [models.Index(fields=['asset', 'component_type'], name='maintenance_asset_i_90136f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assetserviceitem',
            index=models.Index(fields=['asset', 'status'], name='maintenance_asset_i_c236b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetserviceitem',
            constraint=models.UniqueConstraint(fields=('asset', 'definition'), name='unique_asset_service_item'),
        ),
        migrations.AddConstraint(
            model_name='templateitem',
            constraint=models.UniqueConstraint(fields=('template', 'definition'), name='unique_template_item'),
        ),
    ]
