# Generated by Django 6.1 on 2026-08-30 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_assetserviceinfolink_unique_asset_provider_link_and_more'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetserviceitem',
            name='unique_asset_service_item',
        ),
        migrations.RemoveConstraint(
            model_name='templateitem',
            name='unique_template_item',
        ),
        migrations.AddConstraint(
            model_name='assetserviceitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('asset', 'definition'), name='unique_asset_service_item'),
        ),
        migrations.AddConstraint(
            model_name='templateitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('template', 'definition'), name='unique_template_item'),
        ),
    ]
