# Generated by Django 6.1 on 2026-09-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_american_spelling_in_seeded_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetserviceitem',
            options={'ordering': ['sort_order', 'next_due_on', 'definition__name']},
        ),
        migrations.AddField(
            model_name='assetserviceitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
