# Generated by Django 6.1 on 2026-08-30 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, help_text='Links this login to a human, so authored records attribute to a person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='people.person'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetaccess',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='assetaccess',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='unique_asset_access'),
        ),
    ]
