# Generated by Django 6.1 on 2026-09-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('member', 'Member'), ('helper', 'Helper (named vehicles only)')], default='member', max_length=16),
        ),
    ]
