# Generated by Django 6.1 on 2026-08-30 20:14

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_alter_assetspec_source'),
        ('mediafiles', '0002_remove_medialink_unique_media_link_and_more'),
        ('work', '0003_jobitem_service_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserProfile',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('tool_vendor', models.CharField(blank=True, max_length=60)),
                ('tool_model', models.CharField(blank=True, max_length=60)),
                ('version', models.PositiveIntegerField(default=1)),
                ('media_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('text', 'Plain text')], default='pdf', max_length=8)),
                ('engine', models.CharField(blank=True, help_text='Name of a built-in parser, for formats that regex cannot read.', max_length=40)),
                ('fingerprint', models.JSONField(blank=True, default=dict)),
                ('field_extractors', models.JSONField(blank=True, default=dict)),
                ('table_extractor', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('builtin', 'Built in'), ('user', 'Written here'), ('imported', 'Imported')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tool_vendor', 'tool_model', 'name'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('performed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('tool', models.CharField(blank=True, max_length=60)),
                ('tool_model', models.CharField(blank=True, max_length=60)),
                ('odometer', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('odometer_unit', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(choices=[('pdf_report', 'PDF report'), ('file_import', 'Structured file'), ('elm327', 'ELM327 adapter'), ('manual', 'Typed in')], default='pdf_report', max_length=16)),
                ('extracted_text', models.TextField(blank=True)),
                ('extracted_words', models.JSONField(blank=True, default=list)),
                ('parser_version', models.PositiveIntegerField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Not read yet'), ('parsed', 'Read'), ('unmatched', 'No profile matched'), ('failed', 'Could not be read')], default='pending', max_length=12)),
                ('parse_error', models.CharField(blank=True, max_length=255)),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('readiness_monitors', models.JSONField(blank=True, default=dict)),
                ('live_data', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('raw_media', models.ForeignKey(blank=True, help_text='The report as uploaded. Kept forever so it can be re-read.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='mediafiles.media')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_sessions', to='work.workorder')),
                ('parser_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='diagnostics.parserprofile')),
            ],
            options={
                'ordering': ['-performed_on'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodeDescription',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('code', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['make', 'code'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('make', 'code'), name='unique_code_description')],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticCode',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('system', models.CharField(blank=True, max_length=1)),
                ('is_generic', models.BooleanField(default=True)),
                ('module', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(choices=[('stored', 'Stored'), ('pending', 'Pending'), ('permanent', 'Permanent'), ('history', 'History')], default='stored', max_length=12)),
                ('state_raw', models.CharField(blank=True, max_length=120)),
                ('freeze_frame', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('addressed', 'Addressed'), ('recurring', 'Came back'), ('ignored', 'Ignored')], default='open', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by_job_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_codes', to='work.jobitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='diagnostics.diagnosticsession')),
            ],
            options={
                'ordering': ['code'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'indexes': [models.Index(fields=['code', 'status'], name='diagnostics_code_ee377f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='parserprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'version'), name='unique_parser_profile_version'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['asset', '-performed_on'], name='diagnostics_asset_i_cc312f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['review_status', '-created_at'], name='diagnostics_review__b290eb_idx'),
        ),
    ]
