# Generated by Django 6.1 on 2026-08-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserprofile',
            name='source',
            field=models.CharField(choices=[('builtin', 'Shipped'), ('user', 'Written here'), ('imported', 'Imported')], default='user', max_length=10),
        ),
    ]
