# Generated by Django 6.1 on 2026-08-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_alter_parserprofile_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticsession',
            name='source',
            field=models.CharField(choices=[('pdf_report', 'PDF report'), ('file_import', 'Structured file'), ('photo', 'Photo of a printout'), ('elm327', 'ELM327 adapter'), ('manual', 'Typed in')], default='pdf_report', max_length=16),
        ),
        migrations.AlterField(
            model_name='parserprofile',
            name='media_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('text', 'Plain text'), ('image', 'Photo')], default='pdf', max_length=8),
        ),
    ]
