# Generated by Django 6.1 on 2026-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_alter_diagnosticsession_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserprofile',
            name='author',
            field=models.CharField(blank=True, help_text='Who published this profile.', max_length=80),
        ),
        migrations.AddField(
            model_name='parserprofile',
            name='verified_against',
            field=models.CharField(blank=True, help_text='A captured report this profile was proven against. Checked when published, so it is a fact rather than a claim.', max_length=120),
        ),
    ]
