# Generated by Django 6.1 on 2026-09-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_alter_parserprofile_verified_against'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserprofile',
            name='live_data_extractor',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
