# Generated by Django 6.1 on 2026-09-02 15:23

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_rename_is_generic_to_is_iso_sae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledCodeList',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('make', models.CharField(max_length=60)),
                ('slug', models.CharField(blank=True, max_length=64)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['make'],
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('make',), name='unique_installed_code_list')],
            },
        ),
    ]
