# Generated by Django 6.1 on 2026-08-30 06:09

import django.db.models.deletion
import django.utils.timezone
import homeautoshop.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('parts', '0001_initial'),
        ('work', '0002_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('cart', 'Cart'), ('ordered', 'Ordered'), ('partial', 'Partially received'), ('received', 'Received'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='ordered', max_length=12)),
                ('ordered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('received_on', models.DateField(blank=True, null=True)),
                ('tax_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='tax')),
                ('tax_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('shipping_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='shipping')),
                ('shipping_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('discount_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='discount')),
                ('discount_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, help_text='Set when this was bought for a specific job; drives the blocked list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='work.workorder')),
            ],
            options={
                'ordering': ['-ordered_on'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('description_as_ordered', models.CharField(blank=True, max_length=200)),
                ('qty_ordered', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit_price_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='unit price')),
                ('unit_price_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('core_charge_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='core charge')),
                ('core_charge_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='parts.part')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchase')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('online', 'Online'), ('local_store', 'Local store'), ('dealer', 'Dealer'), ('salvage', 'Salvage yard'), ('machine_shop', 'Machine shop'), ('individual', 'Individual')], default='online', max_length=16)),
                ('url', models.URLField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('return_window_days', models.PositiveIntegerField(blank=True, help_text='Used to warn before the window closes.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchasing.vendor'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=homeautoshop.core.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('revision', models.PositiveIntegerField(default=1, editable=False)),
                ('category', models.CharField(choices=[('shop_supplies', 'Shop supplies'), ('outsourced_labor', 'Outsourced labour'), ('machine_work', 'Machine work'), ('towing', 'Towing'), ('disposal', 'Disposal'), ('tooling', 'Tooling'), ('registration', 'Registration'), ('inspection', 'Inspection'), ('insurance', 'Insurance'), ('fuel', 'Fuel'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('amount_minor', models.BigIntegerField(default=0, help_text='Minor units (e.g. cents). Never a float.', verbose_name='amount')),
                ('amount_currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('incurred_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='work.workorder')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='purchasing.vendor')),
            ],
            options={
                'ordering': ['-incurred_on'],
                'indexes': [models.Index(fields=['asset', '-incurred_on'], name='purchasing__asset_i_9462b3_idx')],
            },
        ),
    ]
