# Generated by Django 6.1 on 2026-08-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('ordered', 'Ordered'), ('partial', 'Partially received'), ('received', 'Received'), ('returned', 'Returned'), ('cancelled', 'Canceled')], default='ordered', max_length=12),
        ),
    ]
