# Generated by Django 6.1 on 2026-09-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('shop_supplies', 'Shop supplies'), ('outsourced_labor', 'Outsourced labor'), ('machine_work', 'Machine work'), ('towing', 'Towing'), ('disposal', 'Disposal'), ('tooling', 'Tooling'), ('registration', 'Registration'), ('inspection', 'Inspection'), ('insurance', 'Insurance'), ('fuel', 'Fuel'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
