# Generated by Django 6.1 on 2026-09-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_outsourced_labor_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='A percentage, like 8.4. Leave blank to state the tax as an amount instead.', max_digits=6, null=True, verbose_name='tax rate'),
        ),
    ]
